%token	IDENTIFIER DECIMAL_NUMBER HEXADECIMAL_NUMBER BOOLEAN_TRUE BOOLEAN_FALSE SEMICOLON STRING TYPE NULL_VALUE
%token  PAREN_OPEN PAREN_CLOSE OP_PLUS OP_MINUS OP_MULTIPLY OP_DIVIDE OP_NOT OP_AND OP_OR COMMA
%token  IF ELSE WHILE
%start	Program

%%

Program:	/* empty */
		      | Program IDENTIFIER ;

%%

